AREAS = {
    "local_italy": ["Cannae", "Croton", "Tarentum", "Capua", "Mediolanium", "Aleria", "Arretium", "Kallipolis_Settlement", "Rome", "Segesta", "Cosentia", "Caralis", "Messana", "Lilybaeum", "Syracuse", "Ariminum", "Patavium"],
    "local_gaul": ["Bibracte", "Burdigala", "Darioritum", "Gergovia", "Cenabum", "Samarobriva", "Avaricum", "Lemonum", "Vienna", "Tolosa", "Iuvavum", "Veldideno", "Vesontio", "Vapincum"],
    "local_massilia": ["Massilia"],
    "local_germania": ["Eburonum", "Hafnia", "Valhagarum", "Rugium", "Burgaz_Sueones", "Burgaz_Gothii", "Mattium", "Phabiranum", "Tulisurgium", "Atuatuca", "Teutoburgum", "Sumelocenna"],
    "local_iberia": ["Pallantia", "Bocchoris", "Carthago_Nova", "Saguntum", "Iruna", "Baikor", "Numantia", "Ebora", "Emporion", "Tyde", "Vissalegobor", "Osca", "Arsa", "Gadir"],
    "local_britain": ["Atauna", "Emain_Macha", "Ivernis", "Isurium", "Ictis", "Deva", "Camulodunum"],
    "local_greece": ["Achaea", "Corinth", "Thermon", "Athens", "Kydonia", "Ambracia", "Chalkis", "Sparta", "Mytilene", "Pella", "Elis", "Byzantium", "Rhodes", "Larissa"],
    "local_dacia_illyria": ["Sarmizegetusa", "Apollonia", "Aemona", "Paetovio", "Aquincum", "Singidunum"],
    "local_thracia": ["Naissus", "Sardica", "Seutopolis", "Tomi", "Buridava", ],
    "local_scythia": ["Chersonesos", "Tanais", "Panticapaeum", "Olbia", "Neapolis_Scythica", "Campus_Aorsi", "Vicus_Budinai", "Campus_Iazyges", "Campus_Iirkai", "Campus_Roxolani", "Campus_Siracae", "Vicus_Tissagetae"],
    "local_carthage": ["Hadrumetum", "Tingi", "Hippo_Regius", "Rusadir", "Icosium", "Lepcis_Magna", "Carthage"],
    "local_egypt": ["Augila", "Cyrene", "Axum", "Meroe", "Siwa", "Campus_Blemmye", "Paraetonium", "Memphis", "Alexandria", "Pselchis", "Hibis", "Thebes", "Campus_Noba"],
    "local_africa": ["Rapsa", "Abalassa", "Tuat", "Campus_Tibu", "Talalati", "Siga", "Volubilis", "Cirta", "Masaesylia", "Massylia", "Cydaus", "Dimmidi", "Garbia", "Macomades", "Garama", ],
    "local_anatolia": ["Nicomedia", "Mazaka", "Halicarnasus", "Tarsus", "Salamis", "Ancyra", "Sardis", "Pergamum", "Side", "Ipsus"],
    "local_middle_east": ["Hatra", "Opone", "Damascus", "Jerusalem", "Sidon", "Antioch"],
    "local_arabia": ["Gorda", "Palmyra", "Bostra", "Petra", "Carna", "Gerra", "Omana", "Ubar", "Sabata", "Tamna", "Mariaba"],
    "local_armenia": ["Arbela", "Albana", "Armavir", "Phraaspa", "Mtskheta", "Amida"],
    "local_parthia": ["Campus_Amyrgicum", "Asaak", "Bactra", "Kangha", "Khiva", "Taxila", "Merv", "Kophen", "Maracanda", "Gushan", "Campus_Alanni", "Nisa", "Campus_Massagetae", "Campus_Sakae", "Kashgar", "Chighu"],
    "local_persia": ["Alexandropolis", "Phra", "Seleucia", "Harmozia", "Charax", "Apamea", "Neh", "Susa", "Pura", "Zadracarta", "Ecbatana", "Hecatompylos", "Istakhr", "Opiana", "Patala", "Gabae"],
    "local_pontus": ["Satala", "Kotais", "Sinope", "Amasia"],
    "local_slavs": ["Vicus_Aestii", "Vicus_Careotae", "Vicus_Fenni", "Carrodunum", "Vicus_Venedae", "Vibantavarium", "Leucaristus", "Vicus_Neuri"],
}
 #"seleucid", "parthia", "gauls", "germans", "greek_cities", "greek_syracuse", "greek_sparta", "macedon", "massalia", "pontus", "brennus_host", "romans_julii", 
#"armenia", "dacia", "scythia", "spain", "thrace", "britons", "egypt", "persia", ("carthage_barcid", "carthage_hannonid", "carthage_magonid", )
#"galatia", "tylis", "prausi", "old_ones", "carthage", "slave", "romans_venetii", "sequani", "pictones", "suebi", "chauci", "insubres", "gotini", "cherusci", "kallipolis", 
#"nervii", "namnetes", "caledones", "arevaci", "boii", "romans_etruscans", "massylii", "masaesyli", "berbers", "numidia"
BANNED_IN_AREAS = {
   "local_italy": [],
   "local_gaul": ["britons", "massalia", "carthage", "carthage_barcid", "carthage_hannonid", "carthage_magonid", ],
   "local_massilia": [],
   "local_germania": ["britons", "gauls", "dacia", "scythia", ],
   "local_iberia": ["gauls", ],
   "local_britain": ["gauls", ],
   "local_greece": [],
   "local_dacia_illyria": ["macedon", "scythia", ],
   "local_thracia": ["macedon", "scythia", ],
   "local_scythia": [],
   "local_carthage": ["egypt", ],
   "local_egypt": ["carthage", "carthage_barcid", "carthage_hannonid", "carthage_magonid", ],
   "local_africa": ["carthage", "carthage_barcid", "carthage_hannonid", "carthage_magonid", "egypt", ],
   "local_anatolia": [],
   "local_middle_east": [],
   "local_arabia": ["seleucid", "parthia", "macedon", "pontus", "scythia", "egypt", "persia", "armenia", ],
   "local_armenia": [],
   "local_parthia": ["scythia", ],
   "local_persia": [],
   "local_pontus": [],
   "local_slavs": [],
}
