AREAS = {
    "italy": ["Rhegion", "Taras", "Arpi", "Capua", "Rome", "Arretium", "Ariminum"],
    "sicily": ["Lilibeo", "Messana", "Syracuse"],
    "cisalpine_gaul": ["Patavium", "Bononia", "Mediolanum", "Segesta"],
    "gaul_north": ["Aventicos", "Vesontio", "Bagacos", "Bratosporios", "Cenabum", "Darioritum", "Bibracte"],
    "gaul_south": ["Viennos", "Gergovia", "Tolosa", "Burdigala", "Lemonum", "Avaricum"],
    "massalia": ["Massalia"],
    "iberia_west": ["Gader", "Mastia", "Arse", "Emporion", "Bocchoris", "Baikor"],
    "iberia_east": ["Sucum-Murgi", "Oxtraca", "Tyde", "Pallantia", "Numantia", "Vellika"],
    "britannia": ["Camulosadae", "Ratae", "Caern_Brigantae", "Attuaca", "Ynys_Mon", "Ictis", "Emain_Macha", "Ivernis"],
    "germania": ["Gawjam_Kimbroz", "Gawjam_Habukoz", "Gawjam_Heruskoz", "Arctaunon", "Vindelicoppidos", "Swebotraustastamnoz", "Gawjam_Rugoz", "Gawjam_Skandzawarjoz", "Gawjam_Gotanoz", "Ascaucalis", "Gawjam_Silengoz", "Eburonum", "Carrodunum", "Lucarottea", "Veldideno", "Iuvavoaeta", "Vindobona"],
    "africa_north": ["Lixus", "Siga", "Ippone", "Atiqa", "Kart_Hadast", "Adrumeto", "Lepki"],
    "africa_interior": ["Sala", "Kirtan", "Tuat", "Terhazza", "Garama"],
    "cyrenaica": ["Hibis", "Ammonion", "Paraitonion", "Kyrene", "Augila_settlement"],
    "egypt_north": ["Diospolis_Megale", "Memphis", "Alexandreia"],
    "egypt_south": ["Pselkis", "Meroe", "Ptolemais_Theron", "Axum"],
    "islands": ["Karali", "Alalia", "Kydonia", "Salamis"],
    "arabia": ["Tamane", "Maryab", "Carna", "Sabata", "Ubar", "Homna", "Gerrha", "Petra", "Bostra", "Palmyra"],
    "greece": ["Sparte", "Korinthos", "Athenai", "Chalkis", "Thermon", "Demetrias", "Pella", "Apollonia"],
    "thrace": ["Byzantion", "Tylis", "Serdike"],
    "illyria": ["Epidamnos", "Dalminion", "Segestica"],
    "anatolia": ["Rhodos", "Halikarnassos", "Mytilene", "Pergamon", "Sardis", "Ipsos", "Nikaia", "Ankyra", "Side", "Tarsos", "Mazaka"],
    "armenia": ["Karkathiokerta", "Armavir", "Phraaspa", "Arbela"],
    "pontus": ["Trapezous", "Ani-Kamah", "Sinope", "Amaseia"],
    "dacia": ["Kallatis", "Buridava", "Naissos", "Singidunum", "Sarmiszegethusa", "Ak_Ink"],
    "middle_east": ["Hierosolyma", "Sidon", "Damaskos", "Antiocheia", "Edessa"],
    "sarmatia": ["Chersonesos", "Pantikapaion", "Olbia", "Gawjam_Bastarnoz", "Gordu_Neuriji", "Gintaras_Ostan", "Seliun_Pilis", "Gelonus", "Tanais", "Gava_Yazyga", "Asodat", "Gava_Thissakata", "Gava_Roxsalanna", "Uspe", "Gava_Aursa", "Gava_Yugra", "Kotais", "Mtskheta", "Kabalaka", "Gava_Alanna", "Gava_Saka", "Chighu"],
    "bactria": ["Chach", "Marakanda", "Khiva", "Gava_Mazsakata", "Asaak", "Nisa", "Antiocheia_Margiane", "Baktra", "Alexandreia_Eschate"],
    "mesopotamia": ["Babylon", "Seleukeia", "Charax"],
    "persia": ["Karmana", "Persepolis", "Gabai", "Susa", "Ekbatana", "Apameia", "Hekatompylos", "Zadrakata"],
    "far_east": ["Sulek", "Gava_Haomavarga", "Kophen", "Taksashila", "Alexandropolis", "Opiana", "Patala", "Pura", "Prophthasia", "Alexandreia_Ariana"],
}

#parthia, carthage (pontus), gauls, germans, britons, dacia, greek_cities, egypt (carthage), armenia (scythia), romans_scipii (armenia)
#seleucid (romans), spain, thrace (epirus), pontus (other scythians), scythia (arverni), saba, macedon, numidia (ptolemaioi), romans_julii (seleucid), romans_brutii (baktria)

BANNED_IN_AREAS = {
    "italy": [],
    "sicily": [],
    "cisalpine_gaul": [],
    "gaul_north": ["germans", "britons"],
    "gaul_south": ["spain", "egypt"],
    "massalia": [],
    "iberia_west": ["gauls"],
    "iberia_east": ["gauls", "egypt"],
    "britannia": ["gauls"],
    "germania": ["gauls", "scythia", "dacia", "armenia", "pontus"],
    "africa_north": [],
    "africa_interior": ["egypt"],
    "cyrenaica": ["egypt", "numidia"],
    "egypt_north": [],
    "egypt_south": ["numidia"],
    "islands": [],
    "greece": ["dacia"],
    "thrace": ["greek_cities", "macedon"],
    "illyria": ["greek_cities", "macedon"],
    "anatolia": ["parthia", "greek_cities", "macedon"],
    "armenia": ["armenia", "pontus"],
    "pontus": ["parthia"],
    "dacia": ["germans", "armenia", "pontus", "thrace"],
    "middle_east": ["parthia", "pontus"],
    "sarmatia": ["parthia", "carthage"],
    "bactria": ["romans_julii"],
    "mesopotamia": [],
    "persia": ["armenia", "pontus"],
    "arabia": ["romans_julii", "numidia"],
    "far_east": [],
}
